Repository nextcloud/related_resources, pull requests merged in 2022-09, with the labels that each got.

#2 Use related resources panel from vue library
  package-lock.json
  package.json
  src/components/RelatedResourceItem.vue
  src/main.js
  src/views/RelatedResources.vue
Labels: 3. to review

#18 Enable by default
  appinfo/info.xml
Labels: 3. to review

#33 Bump @nextcloud/vue to update panel in files sidebar
  package-lock.json
  package.json
Labels: 3. to review, design

#43 switch to token
  lib/Db/TalkRoomRequest.php
  lib/RelatedResourceProviders/TalkRelatedResourceProvider.php
Labels: 3. to review, bug

#45 Add command workflows
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
Labels: 3. to review

#53 ignore public share
  lib/Listener/FileShareUpdate.php
Labels: 3. to review, bug, high

#57 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#58 [stable25] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies
