Repository nextcloud/related_resources, pull requests merged in 2022-11, with the labels that each got.

#134 Revert "[stable25] alternate route for complex itemid"
  appinfo/routes.php
  lib/Controller/ApiController.php
Labels: 4. to release

#131 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#132 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#135 Revert "Revert "[stable25] alternate route for complex itemid""
  appinfo/routes.php
  lib/Controller/ApiController.php
Labels: 3. to review

#133 Remove completed remove route TODO
  appinfo/routes.php
Labels: 3. to review

#137 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#138 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#145 [stable25] Bump npm dependencies
  package-lock.json
Labels: 3. to review, dependencies
