Repository nextcloud/related_resources, pull requests merged in 2023-07, with the labels that each got.

#195 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#253 [master] Fix npm audit
  js/related_resources.js
  js/related_resources.js.map
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js.map
  package-lock.json
Labels: 3. to review, dependencies

#258 Create pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#263 [master] Fix npm audit
  js/related_resources.js
  js/related_resources.js.LICENSE.txt
  js/related_resources.js.map
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js.map
  package-lock.json
Labels: 3. to review, dependencies

#247 [stable27] Fix npm audit
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js.map
  package-lock.json
Labels: 3. to review, dependencies

#248 [stable26] Fix npm audit
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js.map
  package-lock.json
Labels: 3. to review, dependencies

#157 [stable25] Update nextcloud/ocp dependency
  .github/workflows/lint-info-xml.yml
  .github/workflows/phpunit-sqlite.yml
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#257 remove useless logs
  lib/Service/RelatedService.php
Labels: backport-request

#264 Update composer dependencies
  composer.json
  composer.lock
Labels: 3. to review, backport-request, dependencies

#262 [stable26] Update nextcloud/ocp dependency
  .github/workflows/lint-info-xml.yml
  .github/workflows/phpunit-sqlite.yml
  composer.lock
Labels: 3. to review, dependencies

#266 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#268 [stable27] Update composer dependencies
  .github/workflows/lint-info-xml.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  composer.json
  composer.lock
Labels: 3. to review, dependencies
