Repository nextcloud/related_resources, pull requests merged in 2023-05, with the labels that each got.

#219 Add npm-audit-fix
  .github/workflows/npm-audit-fix.yml
Labels: 4. to release

#220 [master] Fix npm audit
  package-lock.json
  package.json
Labels: 4. to release, dependencies

#223 [stable26] Fix npm audit
  js/related_resources.js
  js/related_resources.js.map
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js.map
  package-lock.json
  package.json
Labels: 4. to release, dependencies

#221 [stable25] Fix npm audit
  js/related_resources.js
  js/related_resources.js.map
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js.map
  package-lock.json
  package.json
Labels: 4. to release, dependencies

#229 Fix groupfolder icon color
  lib/RelatedResourceProviders/GroupFoldersRelatedResourceProvider.php
Labels: 3. to review

#231 chore(deps): Bump @nextcloud/vue from 7.9.0 to 7.11.6
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js.LICENSE.txt
  js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_js.related_resources.js.map
  package-lock.json
  package.json
Labels: 4. to release, backport-request, bug, dependencies

#237 [master] Fix npm audit
  package-lock.json
Labels: 4. to release, dependencies

#238 fresh session if missing
  lib/RelatedResourceProviders/TalkRelatedResourceProvider.php
  lib/Service/RelatedService.php
Labels: backport-request
